import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root=path.resolve('dist');
const walk=p=>fs.readdirSync(p,{withFileTypes:true}).flatMap(x=>x.isDirectory()?walk(path.join(p,x.name)):[path.join(p,x.name)]);
const files=walk(root).filter(p=>!p.endsWith('sw.js'));const version=crypto.createHash('sha256').update(files.map(p=>fs.readFileSync(p)).join('')).digest('hex').slice(0,12);
const urls=files.map(p=>'/'+path.relative(root,p).replaceAll('\\','/'));
fs.writeFileSync(path.join(root,'sw.js'),`const CACHE='gs-${version}';const FILES=${JSON.stringify(['/',...urls])};
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(FILES)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('gs-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(u.origin!==location.origin||e.request.method!=='GET')return;if(u.pathname.startsWith('/api/')){if(u.pathname!=='/api/coverage')return;e.respondWith(fetch(e.request).then(r=>{if(r.ok){const copy=r.clone();caches.open(CACHE).then(c=>c.put(e.request,copy))}return r}).catch(()=>caches.match(e.request)));return;}e.respondWith(caches.match(e.request).then(c=>c||fetch(e.request)));});`);
console.log('Offline shell:',urls.length,'assets');
