import {useEffect,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import {api} from './api';
export default function LocationMap({onChoose,radius=15,value={},points=[],readOnly=false}){
 const {t,i18n}=useTranslation(),host=useRef(null),mapRef=useRef(null),marker=useRef(null),circle=useRef(null),layer=useRef(null),handler=useRef(onChoose),rev=useRef(0);
 const [mapReady,setMapReady]=useState(false);
 const [message,setMessage]=useState('map_hint'),[query,setQuery]=useState(value.location||''),[results,setResults]=useState([]),[lat,setLat]=useState(value.lat??''),[lon,setLon]=useState(value.lon??''),[busy,setBusy]=useState(false);
 handler.current=onChoose;
 function place(a,b){if(!mapRef.current)return;marker.current?.remove();circle.current?.remove();marker.current=L.marker([a,b],{draggable:!readOnly,icon:L.divIcon({className:'user-pin',html:'●',iconSize:[24,24]})}).addTo(mapRef.current);marker.current.on('dragend',()=>{let p=marker.current.getLatLng();select(p.lat,p.lng)});circle.current=L.circle([a,b],{radius:radius*1000,color:'#165f49',fillOpacity:.05}).addTo(mapRef.current);mapRef.current.setView([a,b],12);}
 async function select(a,b){if(!Number.isFinite(a)||!Number.isFinite(b)||a<8||a>13.7||b<76||b>80.5){setMessage('outside_state');return}const request=++rev.current;setLat(a);setLon(b);place(a,b);setMessage('map_loading');handler.current?.({location:`${a.toFixed(5)}, ${b.toFixed(5)}`,lat:a,lon:b,district:''});try{let data=await api(`/geocode?lat=${a}&lon=${b}`);if(request!==rev.current)return;handler.current?.({...data,lat:a,lon:b});setQuery(data.location);setMessage('map_selected')}catch{if(request===rev.current)setMessage('coordinate_fallback')}}
 useEffect(()=>{const map=L.map(host.current,{center:[10.95,78.45],zoom:7,scrollWheelZoom:false,zoomControl:false,attributionControl:false});mapRef.current=map;layer.current=L.layerGroup().addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18}).on('tileerror',()=>setMessage('tiles_unavailable')).addTo(map);if(!readOnly)map.on('click',e=>select(e.latlng.lat,e.latlng.lng));setMapReady(true);return()=>{rev.current++;map.remove();mapRef.current=null;setMapReady(false)}},[]);
 // Place pin once map is ready AND we have coordinates — fixes auto-load from saved reports
 useEffect(()=>{if(!mapReady)return;if(value.lat!=null&&value.lon!=null){setLat(value.lat);setLon(value.lon);place(value.lat,value.lon);if(readOnly)setMessage('map_selected')}else{marker.current?.remove();circle.current?.remove()}},[value.lat,value.lon,mapReady]);
 useEffect(()=>{layer.current?.clearLayers();points.forEach(p=>{const color=p.kind==='bank'?'#1d4ed8':p.kind==='post_office'?'#a16207':'#b91c1c';const el=document.createElement('div');el.textContent=(p.names?.[i18n.language]||p.name||t(p.kind))+' · '+t(p.kind);L.circleMarker([p.lat,p.lon],{color,radius:7,fillOpacity:.8}).bindPopup(el).addTo(layer.current)})},[points,i18n.language]);
 async function search(){const request=++rev.current;setBusy(true);setMessage('map_loading');try{const r=await api(`/map/search?q=${encodeURIComponent(query)}`);if(request!==rev.current)return;setResults(r.items);setMessage(r.items.length?'choose_place':'no_places')}catch(e){if(request===rev.current)setMessage(e.message==='map_wait'?'map_wait':'map_failed')}finally{setBusy(false)}}
 return <div className="location-map">{!readOnly&&<><label htmlFor="map-search">{t('map_search')}</label><div className="map-search-row"><input id="map-search" value={query} maxLength={200} onChange={e=>setQuery(e.target.value)}/><button type="button" onClick={search} disabled={busy||query.trim().length<2}>{t('search_map')}</button></div>{results.map((r,i)=><button className="map-result" type="button" key={i} onClick={()=>{rev.current++;handler.current?.(r);setResults([]);setMessage('map_selected')}}>{r.location}</button>)}<div className="form-grid"><div><label htmlFor="map-lat">{t('latitude')}</label><input id="map-lat" type="number" step="any" value={lat} onChange={e=>setLat(e.target.value)}/></div><div><label htmlFor="map-lon">{t('longitude')}</label><input id="map-lon" type="number" step="any" value={lon} onChange={e=>setLon(e.target.value)}/></div></div><button type="button" onClick={()=>{if(lat!==''&&lon!=='')select(Number(lat),Number(lon))}}>{t('use_coordinates')}</button></>}
 <p aria-live="polite">{t(message)}</p><div className="actions"><button type="button" onClick={()=>mapRef.current?.zoomIn()}>{t('zoom_in')}</button><button type="button" onClick={()=>mapRef.current?.zoomOut()}>{t('zoom_out')}</button></div><div className="map-surface" ref={host} role="region" aria-label={t('map_label')}/><small>© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap</a> · {t('radius_fixed')}</small></div>;
}
