import {useState} from 'react';
import Loans from './Loans';
import {useTranslation} from 'react-i18next';
import {persist,restore} from './api';
export function saveRepaymentPlan(report){const all=restore('gs-repayment-plans',[]);return persist('gs-repayment-plans',[{id:report.id,category:report.business.category,finance:report.finance},...all.filter(x=>x.id!==report.id)].slice(0,20))}
export default function Tracker(){const {t,i18n}=useTranslation();const [entries,setEntries]=useState(()=>restore('gs-entries',[])),[plans]=useState(()=>restore('gs-repayment-plans',[])),[kind,setKind]=useState('income'),[amount,setAmount]=useState(''),[day,setDay]=useState(()=>new Date().toLocaleDateString('en-CA')),[note,setNote]=useState(''),[error,setError]=useState('');const money=v=>new Intl.NumberFormat(`${i18n.language}-IN`,{style:'currency',currency:'INR',maximumFractionDigits:2}).format(v);const date=v=>new Intl.DateTimeFormat(`${i18n.language}-IN`,{dateStyle:'medium'}).format(new Date(v+'T12:00:00'));const total=k=>entries.filter(e=>e.kind===k).reduce((a,e)=>a+e.paise,0)/100;
function update(next){if(persist('gs-entries',next)){setEntries(next);setError('')}else setError('storage_error')}
function add(e){e.preventDefault();if(!/^\d+(\.\d{1,2})?$/.test(amount)||!Number.isFinite(Number(amount))||Number(amount)<=0||Number(amount)>100000000||!/^\d{4}-\d{2}-\d{2}$/.test(day)||!Number.isFinite(new Date(day).getTime())){setError('invalid_entry');return}const next=[{id:crypto.randomUUID(),kind,paise:Math.round(Number(amount)*100),day,note:note.trim()},...entries];if(persist('gs-entries',next)){setEntries(next);setAmount('');setNote('');setError('')}else setError('storage_error')}
return <section className="tracker-page"><h1>{t('nav_tracker')}</h1><p>{t('tracker_intro')}</p><div className="metrics-grid">{['income','expense'].map(k=><div className="metric" key={k}><span>{t(k)}</span><strong>{money(total(k))}</strong></div>)}<div className="metric accent"><span>{t('cash_balance')}</span><strong>{money(total('income')-total('expense'))}</strong></div></div><form className="panel form-grid" onSubmit={add}><div><label htmlFor="entry-kind">{t('entry_type')}</label><select id="entry-kind" value={kind} onChange={e=>setKind(e.target.value)}>{['income','expense'].map(k=><option key={k} value={k}>{t(k)}</option>)}</select></div><div><label htmlFor="entry-amount">{t('amount')}</label><input id="entry-amount" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></div><div><label htmlFor="entry-date">{t('entry_date')}</label><input id="entry-date" type="date" value={day} onChange={e=>setDay(e.target.value)} required/></div><div><label htmlFor="entry-note">{t('entry_note')}</label><input id="entry-note" maxLength={150} value={note} onChange={e=>setNote(e.target.value)}/></div><button className="primary" type="submit">{t('add_entry')}</button>{error&&<p role="alert">{t(error)}</p>}</form>{entries.length?<div className="table-wrap"><table><caption>{t('nav_tracker')}</caption><thead><tr>{['entry_date','entry_type','amount','entry_note','remove_entry'].map(k=><th key={k}>{t(k)}</th>)}</tr></thead><tbody>{entries.map(e=><tr key={e.id}><td>{date(e.day)}</td><td>{t(e.kind)}</td><td>{money(e.paise/100)}</td><td>{e.note}</td><td><button onClick={()=>update(entries.filter(x=>x.id!==e.id))}>{t('remove_entry')}</button></td></tr>)}</tbody></table></div>:<p>{t('no_entries')}</p>}<Loans/><h2>{t('tracked_plans')}</h2><p>{t('planned_not_sanctioned')}</p>{!plans.length&&<p>{t('no_tracked_plans')}</p>}{plans.map(p=><details className="panel" key={p.id}><summary>{t(`sector.${p.category}`)} · {t(p.finance.scheme)} · {money(p.finance.loan)}</summary><div className="table-wrap"><table><thead><tr><th>{t('due_date')}</th><th>{t('payment')}</th><th>{t('moratorium')}</th></tr></thead><tbody>{p.finance.schedule.map(r=><tr key={r.month}><td>{date(r.due_date)}</td><td>{money(r.payment)}</td><td>{r.moratorium?t('grace'):'—'}</td></tr>)}</tbody></table></div></details>)}</section>}
